apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoligo-app
  labels:
    app: ecoligo-app
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecoligo-app
  template:
    metadata:
      labels:
        app: ecoligo-app
    spec:
      containers:
      - name: ecoligo-app
        image: 398803372580.dkr.ecr.ap-south-1.amazonaws.com/ecoligovenkat:latest
        command: ["uvicorn"]
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15  # Increased for app startup
          periodSeconds: 5
