# Deployment for ecoligo FastAPI application
# Image will be replaced dynamically during deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoligo-app
  labels:
    app: ecoligo-app
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecoligo-app
  template:
    metadata:
      labels:
        app: ecoligo-app
    spec:
      containers:
      - name: ecoligo-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
