# Production deployment pipeline for ecoligo application
# Uses existing Kubernetes manifests with dynamic image tags

name: Production Deployment

on:
  push:
    branches: [main]

env:
  EKS_REGION: us-east-1
  ECR_REGION: ap-south-1
  ECR_REGISTRY: 398803372580.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY: ecoligovenkat
  EKS_CLUSTER: corporate-secondary
  NAMESPACE: ecoligo-production
  APP_NAME: ecoligo-app

jobs:
  build-and-push:
    name: Build and Push Container
    runs-on: self-hosted
    
    outputs:
      image_tag: ${{ steps.tag.outputs.short_sha }}
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials for ECR
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.ECR_REGION }}
        
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ${{ env.ECR_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
        
    - name: Generate image tag
      id: tag
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
        echo "Using immutable image tag: $SHORT_SHA"
        
    - name: Build Docker image
      run: |
        docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag.outputs.short_sha }} .
        
    - name: Push image to ECR
      run: |
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag.outputs.short_sha }}
        echo "Image successfully pushed with tag: ${{ steps.tag.outputs.short_sha }}"

  deploy-to-kubernetes:
    name: Deploy to EKS
    runs-on: self-hosted
    needs: build-and-push
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials for EKS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.EKS_REGION }}
        
    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig \
          --region ${{ env.EKS_REGION }} \
          --name ${{ env.EKS_CLUSTER }}
          
    - name: Create namespace if needed
      run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
        
    - name: Update deployment with current image tag
      run: |
        # Use sed to replace the image tag in the deployment file
        sed -i.bak "s|image:.*|image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ needs.build-and-push.outputs.image_tag }}|" kubernetes/manifests/deployment.yaml
        
    - name: Deploy application
      run: |
        # Apply all manifests from the manifests directory
        kubectl apply -f kubernetes/manifests/ -n ${{ env.NAMESPACE }}
        
    - name: Wait for deployment rollout
      run: |
        echo "Waiting for deployment to complete..."
        kubectl rollout status deployment/${{ env.APP_NAME }} -n ${{ env.NAMESPACE }} --timeout=300s
        
    - name: Verify deployment status
      run: |
        echo "=== Deployment Details ==="
        kubectl get deployment ${{ env.APP_NAME }} -n ${{ env.NAMESPACE }} -o wide
        echo ""
        echo "=== Pods ==="
        kubectl get pods -n ${{ env.NAMESPACE }} -l app=${{ env.APP_NAME }}
        echo ""
        echo "=== Services ==="
        kubectl get service ${{ env.APP_NAME }} -n ${{ env.NAMESPACE }}
        
    - name: Restore original deployment file
      run: |
        # Restore the backup to keep the repository clean
        mv kubernetes/manifests/deployment.yaml.bak kubernetes/manifests/deployment.yaml
        echo "Deployment file restored to original state"
