name: Continuous Integration

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies with uv
      run: |
        uv sync
        uv pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        make unittest
        
    - name: Run linting
      run: |
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        black app/ --check
        
    - name: Build Docker image
      run: |
        docker build -t ecoligo-app:ci-${{ github.sha }} .
        
    - name: Test Docker image
      run: |
        docker run --rm ecoligo-app:ci-${{ github.sha }} python -c "from app.main import app; print('App starts successfully')"
