# CI Pipeline - Code validation and testing
# Runs when someone creates a pull request

name: CI - Test and Validate

on:
  pull_request:
    branches: [main, dev]

jobs:
  test-and-validate:
    name: Run Tests and Validation
    runs-on: self-hosted
    
    steps:
    - name: Get the code
      uses: actions/checkout@v4
      
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install required packages
      run: pip install -r requirements.txt
        
    - name: Run the test suite
      run: |
        echo "Running unit tests..."
        make unittest
        
    - name: Quick application check
      run: |
        python -c "import app; print('Application imports successfully')"
        python -c "from app.main import app; print('FastAPI app loads correctly')"
        
    - name: Build Docker image for testing
      run: |
        docker build -t ecoligo-app-test .
        echo "Docker image builds successfully"
