name: CI Pipeline - Build and Test

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  validate-and-test:
    name: Validate Code and Run Tests
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies with uv
      run: |
        pip install uv
        uv pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        make unittest
      
    - name: Validate application structure
      run: |
        python -c "import app; print('✅ Application imports work')"
        python -c "from app.main import app; print('✅ FastAPI app initializes')"
        
    - name: Build Docker image
      run: |
        docker build -t ecoligo-app:$GITHUB_SHA .
        docker build -t ecoligo-app:latest .
        
    - name: Test Docker container
      run: |
        docker run --rm ecoligo-app:$GITHUB_SHA python -c "import app; print('✅ Docker container works')"
        
    - name: Smoke test application
      run: |
        docker run -d --name smoke-test -p 8000:8000 ecoligo-app:$GITHUB_SHA
        sleep 5
        curl -f http://localhost:8000/ || exit 1
        docker stop smoke-test
        docker rm smoke-test
        
    - name: Test cronjob script
      run: |
        python scripts/hourly_cronjob.py || echo "Cronjob script executed"
